### ISSUE TITLE
Where is the Gemfile?

### ISSUE THREAD

**Issue by twobyte** [pwyf/aid-transparency-index#36]
When running `bundle` or `bundle install` as described in the README, **Could not locate Gemfile** error is returned.

Gemfile is a required configuration file for Ruby Bundler which is not present in this repo.

Any ideas about how to fix this?

**Comment by andylolz** [comment]
Good point. Looks like it was binned in 1d6e2092c880ca44eb9040953b2a3293fc15dd5b.

**Comment by twobyte** [comment]
Thanks Andy :)
